### ISSUE TITLE
Set Meteor settings through METEOR_SETTINGS

### ISSUE THREAD

**Issue by romac** [reminisceme/app#100]
Right now we're setting stuff like the FB and GMaps keys through separate environment variables, and have to put the public part of it into ServiceConfiguration so that the client can access it too. Using `METEOR_SETTINGS` would allow us to retain the flexibility of environment variables while making it easier to use the public settings from the client (via eg. `Meteor.settings.public.gMapsApiKey`).

**Comment by tOverney** [comment]
Since #270, we are now passing some settings to the app via `METEOR_SETTINGS` when deploying (the content of fb_cordova_mobile.json) be careful to combine everything if you decide to put some new things in `METEOR_SETTINGS`
