### ISSUE TITLE
Improve the Timeline question UI further

### ISSUE THREAD

**Issue by romac** [reminisceme/app#103]
The buttons are much better already, good job @Aranir! As you suggested, maybe we can go further though, and display them as a timeline with markers for dates, and a more detailed description of the interval on hover, to give them a more distinct feel from eg. the multiple choice questions.

**Comment by Aranir** [comment]
Could you be more precise? What improvements would you suggest?

**Comment by jrabasco** [comment]
The current UI for them is satisfying.
