### ISSUE TITLE
Post subject about adding multiple photos is not displayed properly

### ISSUE THREAD

**Issue by Rabyss** [reminisceme/app#132]
When there is a post about adding multiple photos, the photos are not displayed. It may be the case that the game creator is to blame. This has to be investigated.

**Comment by romac** [comment]
AFAIK multiple photos are currently not supported (I think we ever mentioned it before). I'll look into it during the holidays. In the meantime, can you post somewhere how the JSON for such a subject looks like?

**Comment by Rabyss** [comment]
The post should have a link to a preview/summary of the pictures and that should be displayed. I'll look into it.

**Comment by Rabyss** [comment]
It was a problem with the way such a post has its picture stored (for some reason it was not in the attachment of the post) which generated subject with links only to the image embedded in Facebook interface. The game-creator now handles it properly and the issue open there is closed. For reference, a JSON for such a post should resemble this:
```
{
    "text": "Ann Onymous added 6 new photos."
    "imageUrl": "https://my.photo.url"
    "facebookImageUrl": "https://my.embed.url"
    "type": "ImagePost"
    "from": {
        "userId": "10203820027762223"
        "userName": "Ann Onymous"
    }
}
```
