### ISSUE TITLE
Zoom function is broken

### ISSUE THREAD

**Issue by Aranir** [reminisceme/app#134]
While moving to Webpack we are moving away from Rockhammer.

Due to this the zoom function is broken:

`$(this.getDOMNode()).zoom(this.props);`

we need to find a different way to implement a zooming function for photos.

**Comment by romac** [comment]
Given how big the images are now and the weird interactions with zoom on mobile, I suggest we leave that aside for now.

**Comment by romac** [comment]
Closing as it is not broken anymore since we completely disabled it. Will open a new ticket in case we want to re-add that feature.
