### ISSUE TITLE
Improve mobile layout

### ISSUE THREAD

**Issue by romac** [reminisceme/app#136]
- [x] Make interface responsive
- [x] Redo the game grid
- [x] Allow inviting friends (eg. in the Play tab)
- [x] Make modals fullscreen on mobile
- [x] Redo the welcome screen
- [x] Improve Account page

**Images:**

<table>
<tr><td>

<img src="https://cloud.githubusercontent.com/assets/106849/18316555/5db8998c-751b-11e6-8f02-d33557085c01.png" />

</td><td>

<img src="https://cloud.githubusercontent.com/assets/106849/18316557/637e76e8-751b-11e6-81d3-1cec6aff8473.png" />

</td></tr></table>

**Comment by tOverney** [comment]
#282 Fixes the welcome screen, unless you speak about the screen with "play with a friend" and "play with a bot" (which can go in another issue).
#279 Fixes the account page, an issue #283 cover what's left to be done.
