### ISSUE TITLE
Cleanup repo files + directory structure

### ISSUE THREAD

**Issue by romac** [reminisceme/app#140]

**Comment by Aranir** [comment]
Please be more precise. What exactly needs cleanup?

**Comment by romac** [comment]
I'd like to straighten the directory structure and remove unnecessary directories like `boot` etc. which we don't need anymore since the move to Webpack.

There's also a lot of files at the root of the repo, and it's not always clear if they are config or scripts, etc.
So it would make sense imho to put them in directories with explicit names like `conf`, `scripts`, etc.
