### ISSUE TITLE
Timeup should be per question

### ISSUE THREAD

**Issue by Aranir** [reminisceme/app#154]
Currently the time is set for the whole tile instead of per question.

It would make more sense to have a timer per question instead of a timer per tile, as if a user had answered already two out of the 3 questions and the time runs out, he would lose the tile.

Therefore a timer per question would be more appropriate.

**Comment by Aranir** [comment]
After internal discussions we decided to have the timeout for all 3 questions, but if the time runs out the user will only send the already answered question. #174

**Comment by romac** [comment]
Subsumed by #174.
