### ISSUE TITLE
ErrorStore currently breaks app if any error occurs

### ISSUE THREAD

**Issue by Aranir** [reminisceme/app#179]
The following line:

```
Promise.onPossiblyUnhandledRejection(this.onPromiseError.bind(this));
```

Breaks the client if any error occurs (as example if the server can't connect to the `game-creator`).
This is especially problematic as it breaks the client in a very confusing way for the user (just a white page instead of loading the application)

Therefor this part has been commented out in 7dbff661d943da3357cad70bcc69b9811632ff27

**Comment by romac** [comment]
Appears to be fixed since 5d2e0ed9b72dccf5f9faec205935316929d105e7.
