### ISSUE TITLE
URLs are not set for every page state

### ISSUE THREAD

**Issue by zommerfelds** [reminisceme/app#185]
Refreshing in a game brings you back to the main page

(P.S. sorry for so many nitpicks :P)

**Comment by romac** [comment]
I can't reproduce this issue on reminisce.me but it indeed appears on https://apps.facebook.com/reminisceme/. I will see if we can store the current game in localstorage to circumvent that.

**Comment by zommerfelds** [comment]
It looks like the issue that I had is fixed now (e.g. it now uses the URL `/play/c863427b5d13939e6d5501d9`). But you are right, on `apps.facebook.com` there is this problem still.
