### ISSUE TITLE
Refusing a bot game creates an invalid phantom game

### ISSUE THREAD

**Issue by jrabasco** [reminisceme/app#195]
Refusing the bot's game requests creates a phantom game (marked as 'DECLINE'). It has two consequences:
1. If you clic on the phantom game you won't be able to enter any other game (despite the displayed URL changing) and will be stuck on the dashboard. This does not happen if you already were in an other valid game (the displayed URL still changes but you remain in your valid game).
2. You don't have a bot invitation anymore.

**Comment by romac** [comment]
Bot doesn't send invites anymore. Postponed until we re-enable that feature.

**Comment by jrabasco** [comment]
The feature is not that useful.
