### ISSUE TITLE
Not possible to launch a new game vs a bot after another game

### ISSUE THREAD

**Issue by BenjaminSchubert** [reminisceme/app#247]
In the image below, there is no "new game" button or at least I couldn't find a way of doing it, without going manually to reminisce.me. A button would be nice,

Thanks !

![screenshot from 2016-12-12 11-49-10](https://cloud.githubusercontent.com/assets/1672192/21096631/0ccdb14c-c061-11e6-9bbf-aebd03b6c722.png)

**Comment by Rabyss** [comment]
This is a UX issue related to #249, I will consolidate those there. Thank you for the feedback.
