### ISSUE TITLE
Re-order questions cannot be reordered

### ISSUE THREAD

**Issue by Rabyss** [reminisceme/app#254]
On some occasion people could not reorder the items, this needs investigation.

**Comment by Rabyss** [comment]
Apparently the items become completely unreactive (the pointer changes shape but clicking does not do anything).

**Comment by Protectator** [comment]
Adding that this doesn't seem to produce any output in the js console.

**Comment by Rabyss** [comment]
Apparently it is completely broken on win10 with chrome.

**Comment by romac** [comment]
Hopefully this has been be fixed by [upgrading](https://github.com/reminisceme/app/commit/8107344f86dff5343a840d9d4201c770f79d568e) to `react-sortable-hoc` v0.4.5. I don't have a Windows 10 VM at hand to test right now, so I will leave the issue open until someone can confirm it now works smoothly.

**Comment by Rabyss** [comment]
I am testing it at the moment, will update.

**Comment by Rabyss** [comment]
It seems to be working. Closing this issue.
