### ISSUE TITLE
Use a proper logging framework on the server

### ISSUE THREAD

**Issue by romac** [reminisceme/app#31]
- https://meteorhacks.com/logging-support-for-meteor
- https://atmospherejs.com/infinitedg/winston
- https://www.loggly.com/blog/managing-a-meteor-application-in-production-three-real-log-management-use-cases/
- http://observatoryjs.com/
- https://atmospherejs.com/superstringsoft/observatory
- https://github.com/tbknl/meteor-trail

**Comment by tOverney** [comment]
@vincenzobaz Haven't you fixed that with winston logs?
