### ISSUE TITLE
Algorithm for bots strategy

### ISSUE THREAD

**Issue by Aranir** [reminisceme/app#37]
The default minmax tic tac toe algorithm will not work in our special case because either it needs to treat specific cases in a different way or becomes computationally too intensive if we generate all possibilities for each move.

The following outline should give an overview of a potential algorithm to create an efficient and sufficiently intelligent strategy to keep games against bots interesting:

### Initial state empty or only one tile conquered

if the board is empty the bot will try to conquer the center tile (highest possibility for a win), if the center tile is already taken it will choose one of the 4 corner tiles at random

### More than 2 tiles conquered

1. The bot will try to score a win (no matter the difficulty of the tile to conquer to do so).
2. The bot will remove the chance of the enemy to win (steal the enemy tile which will reduce the chance to win for the enemy to 0, if not possible try to reduce the possibility for the enemy to win (number of possibilities to have 3 consecutive tiles next turn) to the lowest value, while taking into account the difficulty to conquer the chosen tile.
3. if none of the above cases is present it will try to extend his number of consecutive tiles to the most possible while taking into account the difficulty to conquer the tile.

Any thoughts and additional ideas are welcome.

**Comment by pirroh** [comment]
The high-level strategy sounds correct!
Can you try to expand each step like in this strategy description: http://en.wikipedia.org/wiki/Tic-tac-toe#Strategy
For instance, "1." should be expanded as a set of rules to be tested serially.
Wanna give a shot at the algorithm with just pseudocode?

**Comment by Aranir** [comment]
Here is the first implementation, which doesn't take into account the difficulty of tiles to conquer and basically treats every tile as if fully conquered, except in `winPossible()` and `reduceChanceToWinForOpponent()` which will treat partially conquered tiles as stealable.


##Pseudo Code	

    if (emptyboard()) {
		random(placeCenter(), placeRandomCorner())
	} else if (opponentFirstTurn()) {
		if (opponentPlacedCenter()) {
			placeRandomCorner()
		} else if (opponentPlacedCorner()) {
			placeCenter()
		} else {
			random(placeCenter(), placeCornerNextTo(), opposideEdge())
		}
	} else if (secondTurn() && opponentPlacedCorner()) {
		placeOppositeCorner()
	} else {
		if (winPossible()) {
			tryToWin()
		} else if (opponentWillWin()){
			reduceChanceToWinForOpponent()
		} else {
			if (centerFree()){
				placeCenter()
			} else if (centerBelongsToUs){
				placeRandomSideMiddle()
			} else {
				//uncertain if I missed a case here
				takeRandomCorner()
			}
		}
	}
