### ISSUE TITLE
Disable tile when timer runs out

### ISSUE THREAD

**Issue by romac** [reminisceme/app#57]

**Comment by romac** [comment]
This is already implemented client-side. The client calls the `Answer.timeOut` Meteor method whenever the tile expires. It might not be necessary to add server-side timeout for the moment, as #67 will prevent the user to easily bypass the timer by reloading the page.

**Comment by Aranir** [comment]
For the timeout, the client needs to send not just the gameId but also the tileId which timed out:

`'Answer.timeOut': function(gameId, tileId)`

Server side it is implemented

**Comment by romac** [comment]
Should already be the case: https://github.com/reminisceme/app/blob/master/meteor/client/javascripts/stores/AnswerStore.es6.js

But maybe the property isn't synced correctly with the client, I can investigate tomorrow.

**Comment by romac** [comment]
There was indeed a client-side bug, it's been fixed in https://github.com/reminisceme/app/commit/54293de28af73910097f3ef2503fcb4c5728b0e0.
