### ISSUE TITLE
Handle the "0 correct answers" in the game logic

### ISSUE THREAD

**Issue by pirroh** [reminisceme/app#63]
When a user gets 0 out of 3 correct answers on a tile, we should:
* make sure the user cannot play again on that tile (game logic)
* simply show the 3 parts of the circle in dark gray (UI)

**Comment by Aranir** [comment]
We will add a `disabled` property to each tile on the gameboard to indicate if it already has been played by the user, In addition the server will verify that the user has played a valid tile on the board
