### ISSUE TITLE
Integrate feedback mechanism into the app

### ISSUE THREAD

**Issue by romac** [reminisceme/app#95]
e.g., https://usabilla.com/

**Comment by romac** [comment]
eg. usabilia.com

**Comment by romac** [comment]
https://github.com/ivoviz/feedback

**Comment by romac** [comment]
https://experiments.hertzen.com/jsfeedback/

**Comment by Aranir** [comment]
This has partially been implemented with @1bbc909e257ed38325223461cee49a9995cb9148.

It needs further improvements as images from facebook aren't captured (cors problems), and there seems to be a transparency problem or an z-index problem with the glyph icons.

**Comment by jrabasco** [comment]
This is a sort of duplicate of #255
